# This is a basic workflow to help you get started with Actions

name: Shell Scripts Testing

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      operation:
        description: 'Select any arithmetic operation'
        required: True
        type: choice
        options:
          - 'addition'
          - 'subtract'
          - 'multiply'
          - 'divide'
      param1:
        description: 'First Number'
        required: True
        default: '0'
      param2:
        description: 'Second Number'
        required: True
        default: '0'
     
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shell_scripts
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.7
      
      # Runs a single command using the runners shell
      - name: Run Shell Script
        run: |
              ./calculator.sh "${{ github.event.inputs.operation }}" "${{github.event.inputs.param1}}" "${{github.event.inputs.param2}}"
